/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AcademicIndexRouteImport } from './routes/academic/index'
import { Route as AcademicSplatRouteImport } from './routes/academic/$'
import { Route as ApiHeartbeatRouteRouteImport } from './routes/api/heartbeat/route'
import { Route as ApiPulseRouteRouteImport } from './routes/api/pulse/route'
import { Route as TabsIndexRouteImport } from './routes/tabs/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'

const AcademicRouteLazyRouteImport = createFileRoute('/academic')()
const ProLazyRouteImport = createFileRoute('/pro')()
const SidebarLazyRouteImport = createFileRoute('/sidebar')()
const TabsRouteLazyRouteImport = createFileRoute('/tabs')()
const WorkspaceRouteLazyRouteImport = createFileRoute('/workspace')()
const TabsSplatLazyRouteImport = createFileRoute('/tabs/$')()
const WorkspaceSplatLazyRouteImport = createFileRoute('/workspace/$')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRouteLazyRoute = AcademicRouteLazyRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/academic/route.lazy').then((d) => d.Route),
)
const ProLazyRoute = ProLazyRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pro.lazy').then((d) => d.Route))
const SidebarLazyRoute = SidebarLazyRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sidebar.lazy').then((d) => d.Route))
const TabsRouteLazyRoute = TabsRouteLazyRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tabs/route.lazy').then((d) => d.Route))
const WorkspaceRouteLazyRoute = WorkspaceRouteLazyRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/workspace/route.lazy').then((d) => d.Route),
)
const AcademicIndexRoute = AcademicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicRouteLazyRoute,
} as any)
const AcademicSplatRoute = AcademicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AcademicRouteLazyRoute,
} as any)
const ApiHeartbeatRouteRoute = ApiHeartbeatRouteRouteImport.update({
  id: '/api/heartbeat',
  path: '/api/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseRouteRoute = ApiPulseRouteRouteImport.update({
  id: '/api/pulse',
  path: '/api/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRouteLazyRoute,
} as any)
const TabsSplatLazyRoute = TabsSplatLazyRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => TabsRouteLazyRoute,
} as any).lazy(() => import('./routes/tabs/$.lazy').then((d) => d.Route))
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteLazyRoute,
} as any)
const WorkspaceSplatLazyRoute = WorkspaceSplatLazyRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WorkspaceRouteLazyRoute,
} as any).lazy(() => import('./routes/workspace/$.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/academic': typeof AcademicRouteLazyRouteWithChildren
  '/tabs': typeof TabsRouteLazyRouteWithChildren
  '/workspace': typeof WorkspaceRouteLazyRouteWithChildren
  '/pro': typeof ProLazyRoute
  '/sidebar': typeof SidebarLazyRoute
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/academic/$': typeof AcademicSplatRoute
  '/tabs/$': typeof TabsSplatLazyRoute
  '/workspace/$': typeof WorkspaceSplatLazyRoute
  '/academic/': typeof AcademicIndexRoute
  '/tabs/': typeof TabsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/pro': typeof ProLazyRoute
  '/sidebar': typeof SidebarLazyRoute
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/academic/$': typeof AcademicSplatRoute
  '/tabs/$': typeof TabsSplatLazyRoute
  '/workspace/$': typeof WorkspaceSplatLazyRoute
  '/academic': typeof AcademicIndexRoute
  '/tabs': typeof TabsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/academic': typeof AcademicRouteLazyRouteWithChildren
  '/tabs': typeof TabsRouteLazyRouteWithChildren
  '/workspace': typeof WorkspaceRouteLazyRouteWithChildren
  '/pro': typeof ProLazyRoute
  '/sidebar': typeof SidebarLazyRoute
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/academic/$': typeof AcademicSplatRoute
  '/tabs/$': typeof TabsSplatLazyRoute
  '/workspace/$': typeof WorkspaceSplatLazyRoute
  '/academic/': typeof AcademicIndexRoute
  '/tabs/': typeof TabsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/academic'
    | '/tabs'
    | '/workspace'
    | '/pro'
    | '/sidebar'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/academic/$'
    | '/tabs/$'
    | '/workspace/$'
    | '/academic/'
    | '/tabs/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/pro'
    | '/sidebar'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/academic/$'
    | '/tabs/$'
    | '/workspace/$'
    | '/academic'
    | '/tabs'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/academic'
    | '/tabs'
    | '/workspace'
    | '/pro'
    | '/sidebar'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/academic/$'
    | '/tabs/$'
    | '/workspace/$'
    | '/academic/'
    | '/tabs/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AcademicRouteLazyRoute: typeof AcademicRouteLazyRouteWithChildren
  TabsRouteLazyRoute: typeof TabsRouteLazyRouteWithChildren
  WorkspaceRouteLazyRoute: typeof WorkspaceRouteLazyRouteWithChildren
  ProLazyRoute: typeof ProLazyRoute
  SidebarLazyRoute: typeof SidebarLazyRoute
  ApiHeartbeatRouteRoute: typeof ApiHeartbeatRouteRoute
  ApiPulseRouteRoute: typeof ApiPulseRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs': {
      id: '/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof TabsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/': {
      id: '/academic/'
      path: '/'
      fullPath: '/academic/'
      preLoaderRoute: typeof AcademicIndexRouteImport
      parentRoute: typeof AcademicRouteLazyRoute
    }
    '/academic/$': {
      id: '/academic/$'
      path: '/$'
      fullPath: '/academic/$'
      preLoaderRoute: typeof AcademicSplatRouteImport
      parentRoute: typeof AcademicRouteLazyRoute
    }
    '/api/heartbeat': {
      id: '/api/heartbeat'
      path: '/api/heartbeat'
      fullPath: '/api/heartbeat'
      preLoaderRoute: typeof ApiHeartbeatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse': {
      id: '/api/pulse'
      path: '/api/pulse'
      fullPath: '/api/pulse'
      preLoaderRoute: typeof ApiPulseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/': {
      id: '/tabs/'
      path: '/'
      fullPath: '/tabs/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRouteLazyRoute
    }
    '/tabs/$': {
      id: '/tabs/$'
      path: '/$'
      fullPath: '/tabs/$'
      preLoaderRoute: typeof TabsSplatLazyRouteImport
      parentRoute: typeof TabsRouteLazyRoute
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteLazyRoute
    }
    '/workspace/$': {
      id: '/workspace/$'
      path: '/$'
      fullPath: '/workspace/$'
      preLoaderRoute: typeof WorkspaceSplatLazyRouteImport
      parentRoute: typeof WorkspaceRouteLazyRoute
    }
  }
}

interface AcademicRouteLazyRouteChildren {
  AcademicSplatRoute: typeof AcademicSplatRoute
  AcademicIndexRoute: typeof AcademicIndexRoute
}

const AcademicRouteLazyRouteChildren: AcademicRouteLazyRouteChildren = {
  AcademicSplatRoute: AcademicSplatRoute,
  AcademicIndexRoute: AcademicIndexRoute,
}

const AcademicRouteLazyRouteWithChildren =
  AcademicRouteLazyRoute._addFileChildren(AcademicRouteLazyRouteChildren)

interface TabsRouteLazyRouteChildren {
  TabsSplatLazyRoute: typeof TabsSplatLazyRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteLazyRouteChildren: TabsRouteLazyRouteChildren = {
  TabsSplatLazyRoute: TabsSplatLazyRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteLazyRouteWithChildren = TabsRouteLazyRoute._addFileChildren(
  TabsRouteLazyRouteChildren,
)

interface WorkspaceRouteLazyRouteChildren {
  WorkspaceSplatLazyRoute: typeof WorkspaceSplatLazyRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteLazyRouteChildren: WorkspaceRouteLazyRouteChildren = {
  WorkspaceSplatLazyRoute: WorkspaceSplatLazyRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteLazyRouteWithChildren =
  WorkspaceRouteLazyRoute._addFileChildren(WorkspaceRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AcademicRouteLazyRoute: AcademicRouteLazyRouteWithChildren,
  TabsRouteLazyRoute: TabsRouteLazyRouteWithChildren,
  WorkspaceRouteLazyRoute: WorkspaceRouteLazyRouteWithChildren,
  ProLazyRoute: ProLazyRoute,
  SidebarLazyRoute: SidebarLazyRoute,
  ApiHeartbeatRouteRoute: ApiHeartbeatRouteRoute,
  ApiPulseRouteRoute: ApiPulseRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
